### ISSUE TITLE
Criação de protótipo de alta fidelidade

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#10]
## Descrição da Issue
Criação de protótipo de alta fidelidade

## Tasks:
- [ ] Criação do protótipo

## Critérios de Aceitação:
- [ ] Disponível no figma
- [ ] Disponível na wiki
