### ISSUE TITLE
Documentação do Backlog

### ISSUE THREAD

**Issue by matgomes21** [fga-eps-mds/2022-2-Schedula-Doc#11]
## Descrição da Issue
Criação do artefato de backlog e documentação do mesmo na wiki.

## Tasks:
- [x] Criar o backlog do produto
- [x] Documentar backlog na wiki

## Critérios de Aceitação:
- [x] Artefato completo com as histórias de usuário
- [x] Artefato disponível na wiki
