### ISSUE TITLE
Documento de Plano de Custos

### ISSUE THREAD

**Issue by matgomes21** [fga-eps-mds/2022-2-Schedula-Doc#12]
## Descrição da Issue
Criação do documento de plano de custos do projeto e documentação do mesmo na wiki.

## Tasks:
- [ ] Criação do artefato
- [ ] Documentação do artefato na wiki

## Critérios de Aceitação:
- [ ] Artefato completo e coerente
- [ ] Artefato disponível na wiki
