### ISSUE TITLE
Documentação do planejamento

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#20]
## Descrição da Issue
Documentação do planejamento inicial do projeto

## Tasks:
- [ ] Planejamento de comunicação (Interna e Externa)
- [ ] Agenda de trabalho
- [ ] Ferramentas

## Critérios de Aceitação:
- [ ] Disponível na wiki
