### ISSUE TITLE
Documento de Arquitetura

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#21]
## Descrição da Issue
Atualizar o documento de arquitetura do Schedula

## Tasks:
- [ ] Atualizar documento de arquitetura

## Critérios de Aceitação:
- [ ] Estar de acordo com a arquitetura proposta para o projeto
- [ ] Estar disponível na wiki
