### ISSUE TITLE
Guia de contribuição

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#22]
## Descrição da Issue
Adicionar guia de contribuição na wiki

## Tasks:
- [ ] Criação do guia de contribuição

## Critérios de Aceitação:
- [ ] Seguir os padrões da comunidade de software livre
- [ ] Disponível na wiki
