### ISSUE TITLE
Implementação de testes

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#25]
## Descrição da Issue
Implementação de testes no projeto

## Tasks:
- [ ] Nível unitário
- [ ] Nível de integração
- [ ] Nível de sistema

## Critérios de Aceitação:
- [ ] Devem ser implementados testes em nível unitário, integração e sistema.
