### ISSUE TITLE
Configurar CI/CD

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#4]
## Descrição da Issue
Configuração de CI/CD de todos os serviços da aplicação

## Tasks:
- [ ] CI/CD backend
- [ ] CI/CD frontend

## Critérios de Aceitação:
- [ ] Workflows de CI funcionando
- [ ] Deploys disponíveis para uso
