### ISSUE TITLE
Página inicial Wiki

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#61]
## Descrição da Issue
Fazer introdução do time e do projeto na página inicial da wiki

## Tasks:
- [ ] Apresentar o time
- [ ] Apresentar o projeto
- [ ] Adicionar no readme do repositório de documentação

## Critérios de Aceitação:
- [ ] Estar na wiki
- [ ] Estar no readme do repositório de documentação
