### ISSUE TITLE
Gateway

### ISSUE THREAD

**Issue by thiagompc** [fga-eps-mds/2022-2-Schedula-Doc#78]
## Descrição da Issue
Criação do serviço de gateway que mapeia todas as rotas dos microsserviços do Schedula.

## Tasks:
- [ ] Criação da gateway
- [ ] Mapeamento das rotas do serviço de localidades
- [ ] Mapeamento das rotas do serviço de usuários
- [ ] Mapeamento das rotas do serviço de chamados

## Critérios de Aceitação:
- [ ] Comunicação entre todos os serviços
- [ ] Sistema de autenticação em todas as rotas
